# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    paths:
      - '**/*.cs'
      - '**/*.xaml'
  pull_request:
    paths:
      - '**/*.cs'
      - '**/*.xaml'

jobs:
  build-and-test:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./    # adjust if your .sln/.csproj lives in a subfolder
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('RimworldModTranslator/RimworldModTranslator.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Setup .NET 8.0 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore RimworldModTranslator.sln

      - name: Build solution
        run: dotnet build RimworldModTranslator.sln --no-restore --configuration Release
